### ISSUE TITLE
CI falls workflow_dispatch not supported

### ISSUE THREAD

**Issue by visill** [sanyarnd/java-course-2023#1]
Я скопировал проект и в Actions запустил Build, он упал со следующей ошибкой
Run madrapps/jacoco-report@v1.6.1
Event is workflow_dispatch
Error: Only pull requests and pushes are supported, workflow_dispatch not supported.

**Comment by sanyarnd** [comment]
Попробуйте добавить `if: ( github.event_name != 'workflow_dispatch' )` на 27 строку:

https://github.com/sanyarnd/java-course-2023/blob/main/project-template/.github/workflows/build.yml

**Comment by nesterrovv** [comment]
> Попробуйте добавить `if: ( github.event_name != 'workflow_dispatch' )` на 27 строку:
> 
> https://github.com/sanyarnd/java-course-2023/blob/main/project-template/.github/workflows/build.yml

I added this to myself, now when I run the build in manual mode on my non-master branch, the build is completed, thank you!
